// JavaScript Document
function showsec(sec) {
	if(sec=="spending-showbox-col-1.1"){
		document.getElementById('spending-col-2').style.display="block";
	}
	if(sec=="spending-showbox-col-2.1"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-2.2"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-2.3"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-2.4"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-2.5"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-2.6"){
		document.getElementById('spending-col-3').style.display="block";
	}
	if(sec=="spending-showbox-col-3.1"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.2"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.3"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.4"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.5"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.6"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.7"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-3.8"){
		document.getElementById('spending-col-4').style.display="block";
	}
	if(sec=="spending-showbox-col-4.1"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.2"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.3"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.4"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.5"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.6"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.7"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.8"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.9"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.10"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.11"){
		document.getElementById('spending-col-5').style.display="block";
	}
	if(sec=="spending-showbox-col-4.12"){
		document.getElementById('spending-col-5').style.display="block";
	}
}